# Generated by Django 5.2.3 on 2025-06-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quuestion',
            new_name='Question',
        ),
    ]
