# Generated by Django 5.2.3 on 2025-06-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_category_question_category_name_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category_name',
        ),
    ]
